name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Create Release Folder
      run: rsync -arv --exclude='.git/' --exclude='.github/' --exclude='.gitignore' . ./aws-accelerator-config
    - name: Switch to Release Folder
      run: |
        cd aws-accelerator-config
        ls -la
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #REPO_OWNER: keithweaver
